// ==========================================================================
// 📖 华文智能互动学习阅读器 - 词汇数据库 (data.js)
// ==========================================================================

const lessonTitle = "阿善画凤";

const lessonData = [
    // ===== 第1段 =====
    ["很久以前", "hěn jiǔ yǐ qián", "long long ago", "suatu masa dahulu"],
    ["，", "", "", ""],
    ["南山", "nán shān", "South Mountain", "Gunung Selatan"],
    ["上", "shàng", "on", "di atas"],
    ["住着", "zhù zhe", "lived", "tinggal"],
    ["一个", "yī gè", "a", "seorang"],
    ["少年", "shào nián", "youth", "remaja"],
    ["名叫", "míng jiào", "named", "bernama"],
    ["阿善", "ā shàn", "Ah Shan", "Ah Shan"],
    ["。", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["自小", "zì xiǎo", "since childhood", "sejak kecil"],
    ["跟", "gēn", "with", "dengan"],
    ["爷爷", "yé ye", "grandfather", "datuk"],
    ["学了", "xué le", "learned", "belajar"],
    ["许多", "xǔ duō", "many", "banyak"],
    ["手艺", "shǒu yì", "craftsmanship", "kemahiran"],
    ["，", "", "", ""],
    ["举凡", "jǔ fán", "such as", "seperti"],
    ["刻木", "kè mù", "wood carving", "mengukir kayu"],
    ["、", "", "", ""],
    ["给", "gěi", "for", "untuk"],
    ["村民", "cūn mín", "villagers", "penduduk kampung"],
    ["的", "de", "", ""],
    ["灯笼", "dēng lóng", "lantern", "tanglung"],
    ["画画", "huà huà", "paint", "melukis"],
    ["等", "děng", "etc", "dan lain-lain"],
    ["手艺活儿", "shǒu yì huó ér", "craft work", "kerja kemahiran"],
    ["都", "dōu", "all", "semua"],
    ["难不倒", "nán bù dǎo", "cannot stump", "tidak dapat menyusahkan"],
    ["他", "tā", "him", "dia"],
    ["。", "", "", ""],
    ["阿善", "ā shàn", "Ah Shan", "Ah Shan"],
    ["的", "de", "", ""],
    ["手艺", "shǒu yì", "skill", "kemahiran"],
    ["可", "kě", "really", "sungguh"],
    ["真", "zhēn", "really", "benar-benar"],
    ["了得", "liǎo dé", "amazing", "hebat"],
    ["，", "", "", ""],
    ["画出", "huà chū", "painted", "melukis"],
    ["的", "de", "", ""],
    ["鲤鱼", "lǐ yú", "carp", "ikan koi"],
    ["游", "yóu", "swim", "berenang"],
    ["得", "de", "", ""],
    ["欢", "huān", "joyfully", "dengan riang"],
    ["，", "", "", ""],
    ["画出", "huà chū", "painted", "melukis"],
    ["的", "de", "", ""],
    ["牡丹", "mǔ dān", "peony", "peoni"],
    ["开", "kāi", "bloom", "berbunga"],
    ["得", "de", "", ""],
    ["艳", "yàn", "brightly", "dengan cerah"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    // ===== 第2段 =====
    ["有", "yǒu", "there was", "ada"],
    ["一年", "yī nián", "one year", "satu tahun"],
    ["，", "", "", ""],
    ["村里", "cūn lǐ", "in the village", "di kampung"],
    ["闹了", "nào le", "suffered", "mengalami"],
    ["大雾", "dà wù", "heavy fog", "kabus tebal"],
    ["，", "", "", ""],
    ["明亮", "míng liàng", "bright", "cerah"],
    ["的", "de", "", ""],
    ["天空", "tiān kōng", "sky", "langit"],
    ["变得", "biàn de", "became", "menjadi"],
    ["昏暗", "hūn àn", "dim", "kelam"],
    ["。", "", "", ""],
    ["阿善", "ā shàn", "Ah Shan", "Ah Shan"],
    ["见状", "jiàn zhuàng", "seeing this", "melihat keadaan ini"],
    ["，", "", "", ""],
    ["非常", "fēi cháng", "very", "sangat"],
    ["郁闷", "yù mèn", "depressed", "murung"],
    ["。", "", "", ""],
    ["爷爷", "yé ye", "grandfather", "datuk"],
    ["心疼", "xīn téng", "heartache", "sayang"],
    ["地", "de", "", ""],
    ["问道", "wèn dào", "asked", "bertanya"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["孩子", "hái zi", "child", "anak"],
    ["啊", "a", "", ""],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["这", "zhè", "these", "ini"],
    ["几日", "jǐ rì", "few days", "beberapa hari"],
    ["茶饭不思", "chá fàn bù sī", "cannot eat or drink", "tidak selera makan"],
    ["，", "", "", ""],
    ["有", "yǒu", "have", "ada"],
    ["什么", "shén me", "what", "apa"],
    ["心事", "xīn shì", "worry", "kebimbangan"],
    ["啊", "a", "", ""],
    ["？", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    // ===== 第3段 =====
    ["“", "", "", ""],
    ["爷爷", "yé ye", "Grandfather", "Datuk"],
    ["，", "", "", ""],
    ["大雾", "dà wù", "heavy fog", "kabus tebal"],
    ["不仅", "bù jǐn", "not only", "bukan sahaja"],
    ["让", "ràng", "let", "membuat"],
    ["大人", "dà rén", "adults", "orang dewasa"],
    ["小孩儿", "xiǎo hái ér", "children", "kanak-kanak"],
    ["叫苦连天", "jiào kǔ lián tiān", "complain endlessly", "mengeluh tidak henti"],
    ["；", "", "", ""],
    ["庄稼", "zhuāng jia", "crops", "tanaman"],
    ["枯了", "kū le", "withered", "kering"],
    ["，", "", "", ""],
    ["鸟兽", "niǎo shòu", "birds and beasts", "burung dan binatang"],
    ["也", "yě", "also", "juga"],
    ["失了方向", "shī le fāng xiàng", "lost direction", "hilang arah"],
    ["，", "", "", ""],
    ["一片", "yī piàn", "a", "satu"],
    ["迷蒙", "mí méng", "hazy", "kabur"],
    ["满目", "mǎn mù", "everywhere", "di mana-mana"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    // ===== 第4段 =====
    ["爷爷", "yé ye", "Grandfather", "Datuk"],
    ["叹了口气", "tàn le kǒu qì", "sighed", "mengeluh"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["老天", "lǎo tiān", "Heaven", "Tuhan"],
    ["降", "jiàng", "sends down", "menurunkan"],
    ["雾灾", "wù zāi", "fog disaster", "bencana kabus"],
    ["，", "", "", ""],
    ["大家", "dà jiā", "everyone", "semua orang"],
    ["都", "dōu", "all", "semua"],
    ["如同", "rú tóng", "like", "seperti"],
    ["受刑", "shòu xíng", "suffering punishment", "menerima hukuman"],
    ["啊", "a", "", ""],
    ["！", "", "", ""],
    ["大家", "dà jiā", "everyone", "semua orang"],
    ["都", "dōu", "all", "semua"],
    ["在", "zài", "are", "sedang"],
    ["祈求", "qí qiú", "pray for", "berdoa"],
    ["天晴", "tiān qíng", "clear sky", "langit cerah"],
    ["，", "", "", ""],
    ["可是", "kě shì", "but", "tetapi"],
    ["越求", "yuè qiú", "the more they pray", "semakin berdoa"],
    ["雾越浓", "wù yuè nóng", "the thicker the fog", "semakin tebal kabus"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    // ===== 第5段 =====
    ["“", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["要是", "yào shì", "if", "jika"],
    ["能", "néng", "can", "boleh"],
    ["把", "bǎ", "", ""],
    ["凤凰", "fèng huáng", "phoenix", "phoenix"],
    ["给", "gěi", "", ""],
    ["画活", "huà huó", "paint alive", "melukis hidup"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["让", "ràng", "let", "membuat"],
    ["它", "tā", "it", "ia"],
    ["展翅", "zhǎn chì", "spread wings", "mengembangkan sayap"],
    ["迎日", "yíng rì", "welcome the sun", "menyambut matahari"],
    ["，", "", "", ""],
    ["那", "nà", "that", "itu"],
    ["该", "gāi", "would", "akan"],
    ["多好", "duō hǎo", "how nice", "betapa bagus"],
    ["啊", "a", "", ""],
    ["！", "", "", ""],
    ["可惜", "kě xī", "unfortunately", "malangnya"],
    ["我", "wǒ", "I", "saya"],
    ["从来", "cóng lái", "never", "tidak pernah"],
    ["没", "méi", "not", "tidak"],
    ["见过", "jiàn guò", "seen", "pernah melihat"],
    ["凤凰", "fèng huáng", "phoenix", "phoenix"],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["不知道", "bù zhī dào", "don't know", "tidak tahu"],
    ["凤凰", "fèng huáng", "phoenix", "phoenix"],
    ["住在", "zhù zài", "live in", "tinggal di"],
    ["什么", "shén me", "what", "apa"],
    ["地方", "dì fang", "place", "tempat"],
    ["……", "", "", ""],
    ["”", "", "", ""],
    ["这时", "zhè shí", "at this time", "pada masa ini"],
    ["，", "", "", ""],
    ["爷爷", "yé ye", "grandfather", "datuk"],
    ["想起", "xiǎng qǐ", "remembered", "teringat"],
    ["后山", "hòu shān", "back mountain", "gunung belakang"],
    ["道观", "dào guàn", "Taoist temple", "kuil Tao"],
    ["里", "lǐ", "in", "di"],
    ["有个", "yǒu gè", "there is a", "ada seorang"],
    ["无所不知", "wú suǒ bù zhī", "omniscient", "serba tahu"],
    ["的", "de", "", ""],
    ["老道长", "lǎo dào zhǎng", "old Taoist priest", "paderi Tao tua"],
    ["，", "", "", ""],
    ["便", "biàn", "then", "lalu"],
    ["告诉", "gào su", "told", "memberitahu"],
    ["阿善", "ā shàn", "Ah Shan", "Ah Shan"],
    ["，", "", "", ""],
    ["或许", "huò xǔ", "perhaps", "mungkin"],
    ["找到", "zhǎo dào", "find", "menemui"],
    ["他", "tā", "him", "dia"],
    ["就", "jiù", "then", "lalu"],
    ["能", "néng", "can", "boleh"],
    ["找到", "zhǎo dào", "find", "menemui"],
    ["凤凰", "fèng huáng", "phoenix", "phoenix"],
    ["了", "le", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    // ===== 第6段 =====
    ["第二天", "dì èr tiān", "next day", "hari berikutnya"],
    ["一早", "yī zǎo", "early in the morning", "awal pagi"],
    ["，", "", "", ""],
    ["阿善", "ā shàn", "Ah Shan", "Ah Shan"],
    ["就", "jiù", "then", "lalu"],
    ["到", "dào", "to", "ke"],
    ["道观", "dào guàn", "Taoist temple", "kuil Tao"],
    ["里", "lǐ", "in", "di"],
    ["去", "qù", "go", "pergi"],
    ["找", "zhǎo", "find", "cari"],
    ["老道长", "lǎo dào zhǎng", "old Taoist priest", "paderi Tao tua"],
    ["说明", "shuō míng", "explain", "menjelaskan"],
    ["来意", "lái yì", "purpose of visit", "tujuan lawatan"],
    ["。", "", "", ""],
    ["“", "", "", ""],
    ["南峰顶", "nán fēng dǐng", "South Peak", "Puncak Selatan"],
    ["上", "shàng", "on", "di atas"],
    ["确实", "què shí", "indeed", "memang"],
    ["住着", "zhù zhe", "lives", "tinggal"],
    ["一只", "yī zhī", "a", "seekor"],
    ["老凤凰", "lǎo fèng huáng", "old phoenix", "phoenix tua"],
    ["，", "", "", ""],
    ["可是", "kě shì", "but", "tetapi"],
    ["它", "tā", "it", "ia"],
    ["触犯了", "chù fàn le", "violated", "melanggar"],
    ["天规", "tiān guī", "heavenly rules", "peraturan syurga"],
    ["，", "", "", ""],
    ["天帝", "tiān dì", "Heavenly Emperor", "Maharaja Syurga"],
    ["便", "biàn", "then", "lalu"],
    ["下旨", "xià zhǐ", "issued a decree", "mengeluarkan titah"],
    ["，", "", "", ""],
    ["不准", "bù zhǔn", "not allowed", "tidak dibenarkan"],
    ["它", "tā", "it", "ia"],
    ["在", "zài", "in", "di"],
    ["人前", "rén qián", "before people", "di hadapan orang"],
    ["显形", "xiǎn xíng", "reveal its form", "menampakkan bentuk"],
    ["，", "", "", ""],
    ["这下", "zhè xià", "now", "kini"],
    ["恐怕", "kǒng pà", "afraid", "takut"],
    ["它", "tā", "it", "ia"],
    ["也", "yě", "also", "juga"],
    ["爱莫能助", "ài mò néng zhù", "unable to help", "tidak dapat membantu"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["老道长", "lǎo dào zhǎng", "old Taoist priest", "paderi Tao tua"],
    ["缓缓", "huǎn huǎn", "slowly", "perlahan"],
    ["地", "de", "", ""],
    ["道出", "dào chū", "said", "berkata"],
    ["。", "", "", ""],
    ["阿善", "ā shàn", "Ah Shan", "Ah Shan"],
    ["听了", "tīng le", "heard", "mendengar"],
    ["，", "", "", ""],
    ["虽然", "suī rán", "although", "walaupun"],
    ["难掩", "nán yǎn", "hard to hide", "sukar disembunyikan"],
    ["失落", "shī luò", "disappointment", "kekecewaan"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["还是", "hái shì", "still", "masih"],
    ["决定", "jué dìng", "decided", "memutuskan"],
    ["前去", "qián qù", "go forward", "pergi ke"],
    ["寻找", "xún zhǎo", "look for", "mencari"],
    ["老凤凰", "lǎo fèng huáng", "old phoenix", "phoenix tua"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    // ===== 第7段 =====
    ["隔天", "gé tiān", "the next day", "keesokan harinya"],
    ["，", "", "", ""],
    ["天色", "tiān sè", "sky", "warna langit"],
    ["刚", "gāng", "just", "baru"],
    ["泛起", "fàn qǐ", "appeared", "muncul"],
    ["鱼肚白", "yú dù bái", "fish-belly white", "putih ikan"],
    ["，", "", "", ""],
    ["阿善", "ā shàn", "Ah Shan", "Ah Shan"],
    ["便", "biàn", "then", "lalu"],
    ["前往", "qián wǎng", "headed to", "menuju ke"],
    ["南峰顶", "nán fēng dǐng", "South Peak", "Puncak Selatan"],
    ["。", "", "", ""],
    ["他", "tā", "He", "Dia"],
    ["翻过", "fān guò", "crossed", "melalui"],
    ["一道岭", "yī dào lǐng", "a ridge", "satu rabung"],
    ["，", "", "", ""],
    ["转过", "zhuǎn guò", "turned", "membelok"],
    ["三个弯", "sān gè wān", "three bends", "tiga selekoh"],
    ["，", "", "", ""],
    ["终于", "zhōng yú", "finally", "akhirnya"],
    ["来到了", "lái dào le", "arrived at", "tiba di"],
    ["南峰顶", "nán fēng dǐng", "South Peak", "Puncak Selatan"],
    ["，", "", "", ""],
    ["却", "què", "but", "tetapi"],
    ["惊见", "jīng jiàn", "shocked to see", "terkejut melihat"],
    ["山顶", "shān dǐng", "peak", "puncak"],
    ["已是", "yǐ shì", "already is", "sudah menjadi"],
    ["一片", "yī piàn", "a", "satu"],
    ["荒芜", "huāng wú", "barren", "tandus"],
    ["。", "", "", ""],
    ["阿善", "ā shàn", "Ah Shan", "Ah Shan"],
    ["愁眉不展", "chóu méi bù zhǎn", "frowning", "berkerut dahi"],
    ["之际", "zhī jì", "at the time of", "pada masa"],
    ["，", "", "", ""],
    ["望见", "wàng jiàn", "saw", "melihat"],
    ["一个", "yī gè", "a", "sebuah"],
    ["山洞", "shān dòng", "cave", "gua"],
    ["，", "", "", ""],
    ["于是", "yú shì", "so", "maka"],
    ["打起", "dǎ qǐ", "lit", "menyalakan"],
    ["火炬", "huǒ jù", "torch", "obor"],
    ["往", "wǎng", "into", "ke dalam"],
    ["洞里", "dòng lǐ", "inside the cave", "di dalam gua"],
    ["走去", "zǒu qù", "walk", "berjalan"],
    ["。", "", "", ""],
    ["他", "tā", "He", "Dia"],
    ["见", "jiàn", "saw", "melihat"],
    ["深处", "shēn chù", "deep inside", "di dalam"],
    ["有个", "yǒu gè", "there is a", "ada sebuah"],
    ["瀑布", "pù bù", "waterfall", "air terjun"],
    ["，", "", "", ""],
    ["心生", "xīn shēng", "curious", "timbul"],
    ["好奇", "hào qí", "curiosity", "rasa ingin tahu"],
    ["，", "", "", ""],
    ["便", "biàn", "then", "lalu"],
    ["朝", "cháo", "towards", "ke arah"],
    ["瀑布", "pù bù", "waterfall", "air terjun"],
    ["低处", "dī chù", "lower part", "bahagian bawah"],
    ["看", "kàn", "look", "lihat"],
    ["。", "", "", ""],
    ["“", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["大雾", "dà wù", "foggy", "berkabus"],
    ["天", "tiān", "day", "hari"],
    ["的", "de", "", ""],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["到", "dào", "to", "ke"],
    ["这儿", "zhè ér", "here", "sini"],
    ["来", "lái", "come", "datang"],
    ["做", "zuò", "do", "buat"],
    ["什么", "shén me", "what", "apa"],
    ["？", "", "", ""],
    ["”", "", "", ""],
    ["阿善", "ā shàn", "Ah Shan", "Ah Shan"],
    ["被", "bèi", "by", "oleh"],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["响起", "xiǎng qǐ", "sounded", "berbunyi"],
    ["的", "de", "", ""],
    ["声音", "shēng yīn", "voice", "suara"],
    ["吓得", "xià de", "frightened", "terkejut"],
    ["往前", "wǎng qián", "forward", "ke hadapan"],
    ["跌", "diē", "fall", "jatuh"],
    ["。", "", "", ""],
    ["千钧一发", "qiān jūn yī fà", "critical moment", "saat genting"],
    ["之时", "zhī shí", "when", "apabila"],
    ["，", "", "", ""],
    ["一个", "yī gè", "a", "seorang"],
    ["拄着", "zhǔ zhe", "leaning on", "bersandar pada"],
    ["杖", "zhàng", "cane", "tongkat"],
    ["的", "de", "", ""],
    ["老者", "lǎo zhě", "old man", "orang tua"],
    ["拉住", "lā zhù", "held", "memegang"],
    ["了", "le", "", ""],
    ["他", "tā", "him", "dia"],
    ["！", "", "", ""],
    ["险些", "xiǎn xiē", "almost", "hampir"],
    ["丢命", "diū mìng", "lost life", "hilang nyawa"],
    ["的", "de", "", ""],
    ["阿善", "ā shàn", "Ah Shan", "Ah Shan"],
    ["虽", "suī", "although", "walaupun"],
    ["惊魂未定", "jīng hún wèi dìng", "still in shock", "masih terkejut"],
    ["，", "", "", ""],
    ["仍", "réng", "still", "masih"],
    ["恭恭敬敬", "gōng gōng jìng jìng", "respectfully", "dengan penuh hormat"],
    ["地", "de", "", ""],
    ["道", "dào", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["是", "shì", "am", "ialah"],
    ["来", "lái", "come", "datang"],
    ["找", "zhǎo", "find", "cari"],
    ["老凤凰", "lǎo fèng huáng", "old phoenix", "phoenix tua"],
    ["的", "de", "", ""],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    // ===== 第8段 =====
    ["老者", "lǎo zhě", "The old man", "Orang tua itu"],
    ["笑道", "xiào dào", "laughed", "ketawa"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["南山顶", "nán shān dǐng", "South Peak", "Puncak Selatan"],
    ["早已", "zǎo yǐ", "long ago", "sejak lama"],
    ["荒了", "huāng le", "barren", "tandus"],
    ["，", "", "", ""],
    ["哪儿", "nǎ ér", "where", "mana"],
    ["还有", "hái yǒu", "still have", "masih ada"],
    ["老凤凰", "lǎo fèng huáng", "old phoenix", "phoenix tua"],
    ["呢", "ne", "", ""],
    ["？", "", "", ""],
    ["”", "", "", ""],
    ["“", "", "", ""],
    ["不", "bù", "No", "Tidak"],
    ["！", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["相信", "xiāng xìn", "believe", "percaya"],
    ["老凤凰", "lǎo fèng huáng", "old phoenix", "phoenix tua"],
    ["就", "jiù", "is", "ada"],
    ["在", "zài", "at", "di"],
    ["这儿", "zhè ér", "here", "sini"],
    ["附近", "fù jìn", "nearby", "berhampiran"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["一定", "yī dìng", "must", "mesti"],
    ["要", "yào", "want", "mahu"],
    ["找到", "zhǎo dào", "find", "menemui"],
    ["它", "tā", "it", "ia"],
    ["来", "lái", "come", "datang"],
    ["驱散", "qū sàn", "dispel", "menghalau"],
    ["大雾", "dà wù", "heavy fog", "kabus tebal"],
    ["，", "", "", ""],
    ["救回", "jiù huí", "save back", "menyelamatkan semula"],
    ["村里", "cūn lǐ", "in the village", "di kampung"],
    ["明亮", "míng liàng", "bright", "cerah"],
    ["的", "de", "", ""],
    ["天空", "tiān kōng", "sky", "langit"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    // ===== 第9段 =====
    ["老者", "lǎo zhě", "The old man", "Orang tua itu"],
    ["听了", "tīng le", "heard", "mendengar"],
    ["后", "hòu", "after", "selepas"],
    ["，", "", "", ""],
    ["沉默", "chén mò", "silent", "diam"],
    ["了", "le", "", ""],
    ["半晌", "bàn shǎng", "a while", "seketika"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["阿善", "ā shàn", "Ah Shan", "Ah Shan"],
    ["啊", "a", "", ""],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["就是", "jiù shì", "am", "adalah"],
    ["南山顶", "nán shān dǐng", "South Peak", "Puncak Selatan"],
    ["的", "de", "", ""],
    ["老凤凰", "lǎo fèng huáng", "old phoenix", "phoenix tua"],
    ["。", "", "", ""],
    ["你", "nǐ", "You", "Awak"],
    ["不是", "bù shì", "didn't", "bukankah"],
    ["要", "yào", "want", "mahu"],
    ["画凤凰", "huà fèng huáng", "paint a phoenix", "melukis phoenix"],
    ["吗", "ma", "", ""],
    ["？", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["这就", "zhè jiù", "right away", "sekarang juga"],
    ["现出原形", "xiàn chū yuán xíng", "reveal true form", "menampakkan bentuk asal"],
    ["，", "", "", ""],
    ["让", "ràng", "let", "membuat"],
    ["你", "nǐ", "you", "awak"],
    ["画", "huà", "paint", "melukis"],
    ["我", "wǒ", "my", "saya"],
    ["的", "de", "", ""],
    ["样子", "yàng zi", "appearance", "rupa"],
    ["吧", "ba", "", ""],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["“", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["我", "wǒ", "I", "Saya"],
    ["听说", "tīng shuō", "heard", "mendengar"],
    ["您", "nín", "you", "awak"],
    ["不得", "bù dé", "not allowed", "tidak boleh"],
    ["在", "zài", "before", "di hadapan"],
    ["人前", "rén qián", "people", "orang"],
    ["显形", "xiǎn xíng", "reveal form", "menampakkan bentuk"],
    ["……", "", "", ""],
    ["”", "", "", ""],
    ["阿善", "ā shàn", "Ah Shan", "Ah Shan"],
    ["才", "cái", "just", "baru"],
    ["说到", "shuō dào", "said", "berkata"],
    ["一半", "yī bàn", "half", "separuh"],
    ["，", "", "", ""],
    ["霎时", "shà shí", "instantly", "sekelip mata"],
    ["，", "", "", ""],
    ["山洞", "shān dòng", "cave", "gua"],
    ["里", "lǐ", "in", "di"],
    ["金光闪闪", "jīn guāng shǎn shǎn", "golden light shining", "kilauan cahaya emas"],
    ["，", "", "", ""],
    ["亮晃晃", "liàng huàng huàng", "bright and dazzling", "terang benderang"],
    ["，", "", "", ""],
    ["老者", "lǎo zhě", "old man", "orang tua"],
    ["已", "yǐ", "already", "sudah"],
    ["化成", "huà chéng", "transformed into", "bertukar menjadi"],
    ["神气十足", "shén qì shí zú", "majestic", "megah"],
    ["的", "de", "", ""],
    ["金凤凰", "jīn fèng huáng", "golden phoenix", "phoenix emas"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["“", "", "", ""],
    ["来", "lái", "come", "datang"],
    ["吧", "ba", "", ""],
    ["，", "", "", ""],
    ["画", "huà", "paint", "lukis"],
    ["一只", "yī zhī", "a", "seekor"],
    ["和", "hé", "with", "dengan"],
    ["我", "wǒ", "me", "saya"],
    ["一模一样", "yī mú yī yàng", "exactly the same", "sama betul"],
    ["的", "de", "", ""],
    ["金凤凰", "jīn fèng huáng", "golden phoenix", "phoenix emas"],
    ["。", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    // ===== 第10段 =====
    ["阿善", "ā shàn", "Ah Shan", "Ah Shan"],
    ["又惊又喜", "yòu jīng yòu xǐ", "both surprised and happy", "terkejut dan gembira"],
    ["地", "de", "", ""],
    ["说道", "shuō dào", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["凤爷爷", "fèng yé ye", "Grandpa Phoenix", "Datuk Phoenix"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["一定", "yī dìng", "definitely", "pasti"],
    ["会", "huì", "will", "akan"],
    ["画好", "huà hǎo", "paint well", "melukis dengan baik"],
    ["凤凰像", "fèng huáng xiàng", "phoenix portrait", "potret phoenix"],
    ["！", "", "", ""],
    ["”", "", "", ""],
    ["她", "tā", "he", "dia"],
    ["细细看", "xì xì kàn", "looked carefully", "melihat dengan teliti"],
    ["，", "", "", ""],
    ["牢牢", "láo láo", "firmly", "dengan kukuh"],
    ["记", "jì", "remember", "ingat"],
    ["；", "", "", ""],
    ["动动", "dòng dòng", "touched", "menyentuh"],
    ["玲珑羽", "líng lóng yǔ", "exquisite feathers", "bulu halus"],
    ["，", "", "", ""],
    ["摸摸", "mō mō", "stroked", "mengusap"],
    ["金光尾", "jīn guāng wěi", "golden tail", "ekor keemasan"],
    ["；", "", "", ""],
    ["一边", "yī biān", "one side", "sambil"],
    ["看", "kàn", "look", "lihat"],
    ["，", "", "", ""],
    ["一边", "yī biān", "one side", "sambil"],
    ["画", "huà", "paint", "melukis"],
    ["，", "", "", ""],
    ["加上", "jiā shàng", "plus", "ditambah"],
    ["平日", "píng rì", "usual days", "hari biasa"],
    ["练就", "liàn jiù", "trained", "dilatih"],
    ["的", "de", "", ""],
    ["好手艺", "hǎo shǒu yì", "good craftsmanship", "kemahiran yang baik"],
    ["，", "", "", ""],
    ["顷刻之间", "qǐng kè zhī jiān", "in an instant", "sekelip mata"],
    ["，", "", "", ""],
    ["他", "tā", "he", "dia"],
    ["喜滋滋", "xǐ zī zī", "joyfully", "dengan gembira"],
    ["地", "de", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["凤爷爷", "fèng yé ye", "Grandpa Phoenix", "Datuk Phoenix"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["画好了", "huà hǎo le", "finished painting", "selesai melukis"],
    ["！", "", "", ""],
    ["”", "", "", ""],

    ["\n", "", "", ""], // 👈 第11段

    // ===== 第11段 =====
    ["阿善", "ā shàn", "Ah Shan", "Ah Shan"],
    ["画的", "huà de", "painted", "lukisan"],
    ["凤凰", "fèng huáng", "phoenix", "phoenix"],
    ["：", "", "", ""],
    ["金羽翼", "jīn yǔ yì", "golden wings", "sayap keemasan"],
    ["闪光芒", "shǎn guāng máng", "shining radiance", "berkilauan cahaya"],
    ["，", "", "", ""],
    ["双翼展", "shuāng yì zhǎn", "both wings spread", "kedua sayap terbuka"],
    ["，", "", "", ""],
    ["尾羽舒", "wěi yǔ shū", "tail feathers spread", "bulu ekor terbentang"],
    ["，", "", "", ""],
    ["多", "duō", "how", "betapa"],
    ["神气", "shén qì", "majestic", "megah"],
    ["啊", "a", "", ""],
    ["！", "", "", ""],
    ["老凤凰", "lǎo fèng huáng", "old phoenix", "phoenix tua"],
    ["一看", "yī kàn", "took one look", "sekali pandang"],
    ["，", "", "", ""],
    ["便", "biàn", "then", "lalu"],
    ["念出", "niàn chū", "chanted", "membaca"],
    ["咒语", "zhòu yǔ", "spell", "mantera"],
    ["。", "", "", ""],
    ["画上的", "huà shàng de", "on the painting", "pada lukisan"],
    ["凤凰", "fèng huáng", "phoenix", "phoenix"],
    ["猛然", "měng rán", "suddenly", "tiba-tiba"],
    ["一抖", "yī dǒu", "shook", "menggigil"],
    ["，", "", "", ""],
    ["活啦", "huó la", "came alive", "hidup"],
    ["！", "", "", ""],
    ["它", "tā", "It", "Ia"],
    ["腾空而起", "téng kōng ér qǐ", "soared into the air", "terbang ke udara"],
    ["，", "", "", ""],
    ["在", "zài", "above", "di atas"],
    ["阿善", "ā shàn", "Ah Shan", "Ah Shan"],
    ["头上", "tóu shàng", "head", "kepala"],
    ["左右盘旋", "zuǒ yòu pán xuán", "circling around", "berpusing-pusing"],
    ["。", "", "", ""],
    ["天兵天将", "tiān bīng tiān jiàng", "heavenly soldiers", "tentera syurga"],
    ["看到", "kàn dào", "saw", "melihat"],
    ["凤凰", "fèng huáng", "phoenix", "phoenix"],
    ["，", "", "", ""],
    ["以为", "yǐ wéi", "thought", "menyangka"],
    ["是", "shì", "is", "ialah"],
    ["老凤凰", "lǎo fèng huáng", "old phoenix", "phoenix tua"],
    ["，", "", "", ""],
    ["便", "biàn", "then", "lalu"],
    ["活擒", "huó qín", "captured alive", "menangkap hidup-hidup"],
    ["“", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["”", "", "", ""],
    ["回", "huí", "back", "kembali"],
    ["天宫", "tiān gōng", "Heavenly Palace", "Istana Syurga"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第12段

    // ===== 第12段 =====
    ["老凤凰", "lǎo fèng huáng", "The old phoenix", "Phoenix tua"],
    ["见", "jiàn", "saw", "melihat"],
    ["天兵天将", "tiān bīng tiān jiàng", "heavenly soldiers", "tentera syurga"],
    ["带", "dài", "took", "membawa"],
    ["凤凰", "fèng huáng", "phoenix", "phoenix"],
    ["离开", "lí kāi", "left", "meninggalkan"],
    ["了", "le", "", ""],
    ["南山顶", "nán shān dǐng", "South Peak", "Puncak Selatan"],
    ["，", "", "", ""],
    ["便", "biàn", "then", "lalu"],
    ["再", "zài", "again", "lagi"],
    ["施法", "shī fǎ", "cast a spell", "menggunakan sihir"],
    ["让", "ràng", "let", "membuat"],
    ["大雾", "dà wù", "heavy fog", "kabus tebal"],
    ["散去", "sàn qù", "dispersed", "hilang"],
    ["，", "", "", ""],
    ["南山顶", "nán shān dǐng", "South Peak", "Puncak Selatan"],
    ["重现", "chóng xiàn", "reappeared", "muncul semula"],
    ["阳光", "yáng guāng", "sunlight", "cahaya matahari"],
    ["。", "", "", ""],
    ["从此", "cóng cǐ", "from then on", "sejak itu"],
    ["，", "", "", ""],
    ["大人", "dà rén", "adults", "orang dewasa"],
    ["放心", "fàng xīn", "rest assured", "berasa tenang"],
    ["犁田", "lí tián", "plough the fields", "membajak sawah"],
    ["，", "", "", ""],
    ["小孩儿", "xiǎo hái ér", "children", "kanak-kanak"],
    ["唱着歌谣", "chàng zhe gē yáo", "singing songs", "menyanyi lagu"],
    ["在", "zài", "on", "di"],
    ["草原", "cǎo yuán", "grassland", "padang rumput"],
    ["奔跑", "bēn pǎo", "run", "berlari"],
    ["，", "", "", ""],
    ["村子", "cūn zi", "village", "kampung"],
    ["恢复了", "huī fù le", "restored", "pulih semula"],
    ["以往", "yǐ wǎng", "former", "dahulu"],
    ["的", "de", "", ""],
    ["明亮", "míng liàng", "brightness", "kecerahan"],
    ["与", "yǔ", "and", "dan"],
    ["生气", "shēng qì", "vitality", "kecergasan"],
    ["。", "", "", ""],
];

// 如果使用模块导出，取消下一行注释；若通过 script 标签引入，则全局可用
// export { lessonTitle, lessonData };
